name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "fileName.txt"
          FILE_DATA: "file content"
      - name: Push bundle on release
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Rollup robot
          new_branch: 'release'