name: Test workflow

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed

jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "fileName.txt"
          FILE_DATA: "file content"
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Push bundle on tag ${{ steps.get-latest-tag.outputs.tag }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Rollup robot
          new_branch: '${{ steps.get-latest-tag.outputs.tag }}'