name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  rollup:
    runs-on: ubuntu-latest

    steps:
      - name: Merge main -> release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Create bundle
        run: npm run rollup
      - name: Push bundle on release
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Rollup robot
          new_branch: 'release'