name: Test workflow

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed

jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Use tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}
